---

- hosts: all
  become: true
  tasks:

  - name: install httpd package with php and update_cache
    package:
      name: 
        - httpd
        - php
      state: latest
      update_cache: yes
