---

- hosts: all
  become: true
  tasks:
  - name: install update
    yum:
      update_only: yes
      update_cache: yes

- hosts: http_server   
  become: true
  tasks:
  - name: install httpd package with php
    package:
      name: 
        - httpd
        - php
      state: latest

- hosts: db_server
  become: true
  tasks:
  - name: install Maria DB
    package:
      name:
        - mariadb
      state: latest
